import { test, expect } from '@playwright/test';
//rating prob
test('test', async ({ page }) => {
  await page.goto('https://susticket-main.vercel.app/');
  await page.getByRole('img', { name: '~/assets/header/' }).click();
  await page.getByRole('button', { name: 'Log out' }).click();
  await page.locator('form div').nth(2).click();
  await page.locator('form div').nth(2).click();
  await page.getByPlaceholder('Student/Faculty ID').fill('12111428');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('12111428');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div').filter({ hasText: /^My Tickets$/ }).click();
  await page.locator('div').filter({ hasText: /^My Tickets$/ }).getByRole('img').click();
  await page.getByRole('button', { name: 'My Tickets' }).click();
  await page.locator('[id="__nuxt"] div').filter({ hasText: 'Basketball CompetitionApril' }).nth(4).click();
  await page.getByRole('heading', { name: 'Basketball Competition' }).click();
  await page.getByText('April 29, 2024 | 12:00AM BJT').click();
  await page.getByText('Faculty Apartment Basketball').click();
  await page.getByRole('heading', { name: '¥30' }).click();
  await page.getByRole('img', { name: 'event-image' }).nth(1).click();
  await page.locator('div:nth-child(2) > .right > .bookmark-share > .share').click();
  // await page.getByRole('button', { name: 'Give Comment' }).nth(1).click();
  // await page.getByLabel('rating').getByRole('img').nth(2).click();
  // // await page.getByPlaceholder('Share your thoughts about').click();
  // await page.getByPlaceholder('Share your thoughts about').fill('wasaii');
  // await page.getByRole('button', { name: 'Click to upload' }).click();
  // await page.getByRole('button', { name: 'Click to upload' }).setInputFiles('20240528_170123.jpg');
  // await page.getByRole('button', { name: 'Submit' }).click();
  // await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('img', { name: 'event-image' }).nth(1).click();
  await page.getByRole('heading', { name: 'Basketball Competition' }).click();
  await page.getByText('ANother fun eventMarch 30, 2024 | 12:00AM BJTSwimming Pool 2¥50Give Comment').click();
  await page.getByText('ANother fun eventMarch 30,').click();
  await page.getByRole('heading', { name: 'ANother fun event' }).click();
  await page.getByText('March 30, 2024 | 12:00AM BJT').click();
  await page.getByText('Swimming Pool').click();
  await page.getByRole('heading', { name: '¥50' }).click();
  await page.getByRole('img', { name: 'event-image' }).first().click();
  await page.locator('div').filter({ hasText: /^ANother fun eventMarch 30, 2024 \| 12:00AM BJTSwimming Pool 2¥50Give Comment$/ }).locator('div').first().click();
  await page.locator('div').filter({ hasText: /^ANother fun eventMarch 30, 2024 \| 12:00AM BJTSwimming Pool 2¥50Give Comment$/ }).getByRole('img').nth(1).click();
  await page.locator('div').filter({ hasText: /^ANother fun eventMarch 30, 2024 \| 12:00AM BJTSwimming Pool 2¥50Give Comment$/ }).getByRole('button').click();
  await page.locator('span:nth-child(3) > .el-icon > svg > path').first().click();
  await page.getByRole('button', { name: 'Click to upload' }).click();
  await page.getByRole('button', { name: 'Click to upload' }).setInputFiles('20240528_170123.jpg');
  await page.getByPlaceholder('Share your thoughts about').click();
  await page.getByPlaceholder('Share your thoughts about').fill('heii');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
});